### ISSUE TITLE
feat: validation to only support one UNI per proxy port

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/telemetry_int#110]
Related to https://github.com/kytos-ng/telemetry_int/issues/109

This is to provide validation to only support one UNI per proxy port and decide on the side effects that will be performed (probably will be similar to a `proxy_port` metadata removed if what's being configured isn't supported).

**Comment by italovalcy** [comment]
Hi @viniarck ,

As we discussed through Slack, strategy 1 seems fine to me. Proposal 2, IMHO, could lead to accidental mistakes: the operator changes the proxy_port to a port that another EVC is already using, and then suddenly, the telemetry stops working. We will only notice if we have one additional step of checking the logs or checking the list of telemetry enabled EVCs.

Adding some sanity checks to the proxy_port change process guarantees that mistakes in the regular operation (i.e., changes through the proper REST API) are immediately identified. One approach, as we discussed on Slack, would be to change the proxy port via the telemetry INT endpoint, which would do some sanity checks and then act as a wrapper to the topology metadata change API. Additionally, the event validation proposed in item 2 above could also guarantee consistency across other change processes (e.g., someone changing the proxy port metadata directly through topology API -- although eventually, we should have means to protect metadata that are internal to Kytos operation).

I understand this would impact the release plan, so feel free to decide which option fits better.
