### ISSUE TITLE
feat: specify endpoints to validate and manage a `proxy_port` of an interface

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/telemetry_int#112]
This is to cover https://github.com/kytos-ng/telemetry_int/issues/110#issuecomment-2245941762

It'll be delivered as a patch for `2024.1`. 

The endpoint(s) and payloads will be specified here later.

**Comment by viniarck** [comment]
Here are the new three proposed endpoints to provide this functionality:

- [`POST /v1/uni/{interface_id}/proxy_port/{port_number}`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml#L189-L190)
- [`DELETE /v1/uni/{interface_id}/proxy_port/{port_number}`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml#L229)
- [`GET /v1/uni/proxy_port`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml#L173-L174)

If you copy and paste [`openapi.yml`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml) on https://editor.swagger.io/, you can also see it rendered. Check out the descriptions in the API for more information about what it does. 

@italovalcy, let me know if you'd like any other detail to be changed or included

**Comment by italovalcy** [comment]
> Here are the new three proposed endpoints to provide this functionality:
> 
> * [`POST /v1/uni/{interface_id}/proxy_port/{port_number}`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml#L189-L190)
> * [`DELETE /v1/uni/{interface_id}/proxy_port/{port_number}`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml#L229)
> * [`GET /v1/uni/proxy_port`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml#L173-L174)
> 
> If you copy and paste [`openapi.yml`](https://github.com/kytos-ng/telemetry_int/blob/feat/proxy_port_endpoints/openapi.yml) on https://editor.swagger.io/, you can also see it rendered. Check out the descriptions in the API for more information about what it does.
> 
> @italovalcy, let me know if you'd like any other detail to be changed or included

Awesome, Vinicius! seems fine to me!

**Comment by viniarck** [comment]
Appreciated your review/feedback, Italo. 

New minor proposed changes enhancement:

- `DELETE /v1/uni/{interface_id}/proxy_port/{port_number}` as `DELETE /v1/uni/{interface_id}/proxy_port/` (no need to pass port_number) value for deletion, since there can be only one `proxy_port` per UNI, it simplifies also for the caller and makes it easier to understand
- Include interface and proxy port source `status` and `status_reason` on `GET /v1/uni/proxy_port`
